# Generated by Django 2.0.5 on 2018-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('market', models.CharField(max_length=500)),
                ('alert', models.CharField(max_length=100)),
                ('alert_details', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
